### ISSUE TITLE
延迟队列CPU占用高

### ISSUE THREAD

**Issue by hhrensheng** [workbunny/webman-rqueue#10]
启动两个消费QueueBuilder，一个延迟的一个非延迟的。在都没有进行消费的时候延迟QueueBuilder的CPU占用相比非延迟QueueBuilder差距很大，请问是因为延迟QueueBuilder内定时器的原因吗
![WX20240201-172140](https://github.com/workbunny/webman-rqueue/assets/29398035/f41fba49-7ab4-4b01-a12e-320035e65575)

硬件配置
2vCPU 2.0GHz

**Comment by hhrensheng** [comment]
![image](https://github.com/workbunny/webman-rqueue/assets/29398035/23cd4cc1-18b0-4a50-84f3-eaacfd3c3f4c)

**Comment by hhrensheng** [comment]
应该是这个原因，我把$timerInterval消费间隔改成1秒占用就下来了

**Comment by chaz6chez** [comment]
1. 队列的消费利用的是event-loop的timer
2. 延迟队列是利用消息的delay的判断+消息的republish来模拟的

所以延迟队列在消费间隔较小的时候会频繁对延迟队列的消息进行滚动，反复read+republish，直到delay条件达到；在这个情况下，CPU会占用较高，一方面是redis本身压力会增加，一方面是队列在接近空转的情况下处理；

所以：
1. 延迟队列尽可能消费间隔大一些
2. 不同的延迟任务尽可能分散在不同消费间隔的延迟队列【可选项建议】

**Comment by chaz6chez** [comment]
计划在下一个版本增加自适应定时间隔：
1. 增加闲置间隔idle_limit配置参数，接受一个int，单位ms
2. 增加退避指数avoid_index配置，接受一个float
3. 增加最大退避间隔avoid_interval配置，接受一个float，单位ms
4. 优化当前定时消费为自适应定时消费

当idle_limit时间内没有读取到任何消息时，当前消费进程的定时器会根据退避指数avoid_index倍数增加自己的定时器间隔，每增加一次间隔后的下一次如果依然没有读取到消息，则定时器间隔呈avoid_index指数倍数上升；
定时器间隔不会超过最大退避间隔；
当任意一次消息被读取后，定时器间隔恢复初始化。

**Comment by hhrensheng** [comment]
感谢作者的答疑。自适应的这种效果确实不错，现在默认的1ms间隔确实太短了，如果不修改的话，一般云服务器大部分都是低主频确实容易高占用。

**Comment by chaz6chez** [comment]
2.1.10版本开始增加了自适应队列，是一个实验性质的功能特性，待成熟后，会在2.2中正式加入
