### ISSUE TITLE
非延迟队列设置timerInterval 显示busy

### ISSUE THREAD

**Issue by hhrensheng** [workbunny/webman-rqueue#11]
非延迟队列修改$timerInterval后重启，运行php start.php status显示如下
![image](https://github.com/workbunny/webman-rqueue/assets/29398035/8be42cf7-01af-483f-8207-1e27078fae54)

**Comment by chaz6chez** [comment]
1. 使用workerman官方文档的busy排查方案，上传一下busy相关的信息
2. 上传一下该队列的配置信息，包括QOS、timerInterval等参数

**Comment by hhrensheng** [comment]
![image](https://github.com/workbunny/webman-rqueue/assets/29398035/d10cc98f-9b6b-4d7b-8823-35d347248ae4)
`strace -ttp 18881` 
![image](https://github.com/workbunny/webman-rqueue/assets/29398035/5c58995f-9975-4552-ae82-cc393ed8594b)
`lsof -nPp 18881` 
![image](https://github.com/workbunny/webman-rqueue/assets/29398035/9392cdab-f715-4f02-a372-ed34a07c2c28)

代码配置
![image](https://github.com/workbunny/webman-rqueue/assets/29398035/b8d62051-2fd1-409d-8ddd-7132a948df19)

**Comment by hhrensheng** [comment]
redis 的connection是正常的，延迟队列也是用的这个配置是没有问题的

**Comment by chaz6chez** [comment]
你的队列看起来很正常，没问题；
poll timeout是正常的；
我进行测试后，没有复现你的问题，是否能给一个稳定的测试样例？

尝试使用status -d观察是否长时间busy

**Comment by hhrensheng** [comment]
status -d 刚开始是busy 然后就正常了。如果不加-d 就是busy

**Comment by chaz6chez** [comment]
status是定时器捕获状态，假设在workman事件刚好发生阻塞事件（php大多数io都是阻塞的，如PDO），那么就会显示busy；
-d是轮询查询，所以能观察的更仔细；
刚开始busy，我认为是redis创建连接等阻塞操作造成的，当连接成功创建后，消费者的timer就正常进行消费了，如你的timer handler中存在阻塞，那么这个时候进行status查询，也将会是busy，直到handler执行完，workerman的event就将接管业务。
