### ISSUE TITLE
 _header['_delete'] 消息释放如何理解？

### ISSUE THREAD

**Issue by iYting** [workbunny/webman-rqueue#12]
在Builder里`return true` 代表这个某个任务消费完成，文档上描述 **每一次消费之后会根据消息的属性 _header['_delete'] 来进行消息释放**  应该如何理解呢？

**Comment by chaz6chez** [comment]
redis-stream中，对于group来说，消息的消费只是游标的迁移，并没有将消息实体移除，只要消息没有被移除，其他group还可以获取到；delete是将消息移除的标记，在queueBuilder中，一般group与队列是一对一关系，所以使用delete自动移除；在groupBuilder中，group与队列是多对一关系，需要等待最后一个group消费完毕再移除消息。
