### ISSUE TITLE
在异常消息入库的时候，初始化的表created_at 字段和 插入数据时字段不一致，希望可以修复。

### ISSUE THREAD

**Issue by huizhou-fack** [workbunny/webman-rqueue#13]
![image](https://github.com/user-attachments/assets/9ee0a0d1-aaac-4a8f-9767-ef0a0e3025f4)

![image](https://github.com/user-attachments/assets/6cafcc7e-05d0-439f-9392-b71e63a4c992)

创建时间字段不对齐

**Comment by chaz6chez** [comment]
感谢！
尝试更新到最新版本，并移除runtime路径下的db文件
