### ISSUE TITLE
支持php8.0+吗?

### ISSUE THREAD

**Issue by huihui14569** [workbunny/webman-rqueue#3]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires workbunny/webman-rqueue * -> satisfiable by workbunny/webman-rqueue[0.0.1, 0.0.2, 1.0.0, 1.0.1].
    - workbunny/webman-rqueue[0.0.1, ..., 0.0.2, 1.0.0, ..., 1.0.1] require psr/container ^1.1.1 -> found psr/container[1.1.1, 1.1.2] but it conflicts with your root composer.json require (^2.0).

You can also try re-running composer require with an explicit version constraint, e.g. "composer require workbunny/webman-rqueue:*" to figure out if any version is installable, or "composer require workbunny/webman-rqueue:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

好像不支持php8.0 我用了psr/container(^2.0)

**Comment by chaz6chez** [comment]
我尝试调整了composer.json，请使用最新版本试试
